apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world
  namespace: abb  # Assigning the namespace
  labels:
    app: java-hello-world
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: java-hello-world
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      securityContext:  # Security context at the Pod level
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: java-hello-world
          image: devopsmaster.azurecr.io/java-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          securityContext:  # Security context at the Container level
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
