trigger:
  branches:
    include:
      - main  # Runs when code is pushed to main

pr:
  branches:
    include:
      - main  # Runs PR validation before merging into main

pool:
  name-adopool  

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build and Test Job"
        steps:
          - template: templates/install-dependencies.yml
          - template: templates/run=tests.yml
          - template: templates/build-app.yml

  - stage: Publish
    displayName: "Publish Stage"
    jobs:
      - job: PublishJob
        displayName: "Publish Build Artifacts"
        steps:
          - template: templates/publish-artifact.yml